// verify/next/src/app/page.tsx
/* --------------------------------------------------------------------------------------------
 * Copyright (c) 2024 TypeFox and others.
 * Licensed under the MIT License. See LICENSE in the package root for license information.
 * ------------------------------------------------------------------------------------------ */

'use client';

import dynamic from 'next/dynamic';
import { buildJsonClientUserConfig } from 'monaco-languageclient-examples/json-client';

const DynamicMonacoEditorReact = dynamic(() => import('@typefox/monaco-editor-react').then(mod => mod.MonacoEditorReactComp), {
    ssr: false,
});

export default function Page() {
    // const wrapperConfig = buildWrapperConfig();
    const wrapperConfig = buildJsonClientUserConfig();
    return (
        <div style={{ 'height': '80vh', padding: '5px' }} >
            <DynamicMonacoEditorReact
                style={{ 'height': '100%' }}
                wrapperConfig={wrapperConfig} />
        </div>
    );
}

// verify/angular/src/app/app.component.ts
/* --------------------------------------------------------------------------------------------
 * Copyright (c) 2024 TypeFox and others.
 * Licensed under the MIT License. See LICENSE in the package root for license information.
 * ------------------------------------------------------------------------------------------ */

import { AfterViewInit, Component, signal } from '@angular/core';
import { WrapperConfig } from 'monaco-editor-wrapper';
import { MonacoAngularWrapperComponent } from '../monaco-angular-wrapper.component';
import { buildJsonClientUserConfig } from 'monaco-languageclient-examples/json-client';
import '@codingame/monaco-vscode-groovy-default-extension';
@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
    standalone: true,
    imports: [MonacoAngularWrapperComponent],
})
export class AppComponent implements AfterViewInit {
    wrapperConfig: WrapperConfig | undefined;
    title = 'angular-client';

    readonly codeText = signal('');


    async ngAfterViewInit(): Promise<void> {
        const config = buildJsonClientUserConfig({
            htmlContainer: document.getElementById('monaco-editor-root')!,
        });
        this.wrapperConfig = config;
    }

    onTextChanged(text: string) {
        this.codeText.set(text);
    }
}


<h2>Monaco Language Client Angular Client Two way data binding Example</h2>
<div>
    @if(wrapperConfig) {
    <monaco-angular-wrapper
        [wrapperConfig]="wrapperConfig"
        (onTextChanged)="onTextChanged($event)"
    ></monaco-angular-wrapper>

    }

    {{ codeText() }}
</div>
